[config]
  skip_core_tasks = true

[tasks.default]
  dependencies = ["build"]

[tasks.build]
  dependencies = ["prepare", "release", "debug"]

[tasks.test]
  command = "node"
  args    = ["--test", "../reference.test.mjs"]

[tasks.format]
  command = "clang-format"
  args = [
    "-i",
    "src/output.h",
    "src/output.cc",
    "src/utils.h",
    "src/utils.cc",
    "src/reference.cc",
    "src/readme.cc",
  ]

[tasks.clean]
  command = "rm"
  args    = ["-r", "-f", "dist"]

[tasks.verify]
  dependencies = ["format", "clean", "build", "test", "readme", "readme:run"]

[tasks.readme]
  command = "clang++"
  args = [
    "-std=c++11",
    "-I",
    "../../parser/dist/cpp/release",
    "-o",
    "dist/readme",
    "../../parser/dist/cpp/release/libmilo.a",
    "src/output.cc",
    "src/utils.cc",
    "src/readme.cc",
  ]

[tasks."readme:run"]
  command = "./dist/readme"

[tasks.prepare]
  script = ["mkdir -p dist", "rm -rf dist/*"]

[tasks.release]
  command = "clang++"
  args = [
    "-std=c++11",
    "-I",
    "../../parser/dist/cpp/release",
    "-o",
    "dist/reference-release",
    "../../parser/dist/cpp/release/libmilo.a",
    "src/output.cc",
    "src/utils.cc",
    "src/reference.cc",
  ]

[tasks.debug]
  command = "clang++"
  args = [
    "-std=c++11",
    "-I",
    "../../parser/dist/cpp/debug",
    "-o",
    "dist/reference-debug",
    "../../parser/dist/cpp/debug/libmilo.a",
    "src/output.cc",
    "src/utils.cc",
    "src/reference.cc",
  ]
