[env]
  COMMON_CC = "src/output.cc src/utils.cc"

[config]
  skip_core_tasks = true

[tasks.default]
  dependencies = ["all"]

[tasks.verify]
  dependencies = ["clean", "all", "test"]

[tasks.all]
  dependencies = ["release", "debug"]

[tasks.clean]
  script = "rm -rf dist lib tmp"

[tasks.test]
  dependencies = ["all"]
  command      = "node"
  args         = ["--test", "../reference.test.mjs"]

[tasks.release]
  env      = { CONFIGURATION = "release" }
  run_task = [{ name = ["lib", "executable"] }]

[tasks.debug]
  env      = { CONFIGURATION = "debug" }
  run_task = [{ name = ["lib", "executable"] }]

[tasks.executable]
  script = [
    "mkdir -p dist",
    "clang++ -std=c++11 -I lib/${CONFIGURATION} -o dist/reference-${CONFIGURATION} lib/${CONFIGURATION}/libmilo.a ${COMMON_CC} src/main.cc",
  ]

[tasks.lib]
  script = [
    "mkdir -p lib/${CONFIGURATION}",
    "cd ../../parser",
    "makers cpp-${CONFIGURATION}",
    "cp -a dist/cpp/${CONFIGURATION}/libmilo.a dist/cpp/${CONFIGURATION}/milo.h ../references/cpp/lib/${CONFIGURATION}",
  ]
