language      = "C++"
include_guard = "MILO_H"
namespace     = "milo"

[parse.expand]
  crates = ["milo"]

[export]
  include = [
    "Parser",
    "ParserCallbacks",
    "Flags",
    "CStringWithLength",
    "Callback",
    "MessageTypes",
    "Connections",
    "Methods",
    "States",
    "Errors",
  ]
