[config]
  skip_core_tasks = true

[tasks.default]
  dependencies = ["bench"]

[tasks.test]
  command = "cargo"
  args    = ["test"]

[tasks.lint]
  command = "cargo"
  args    = ["clippy"]

[tasks."lint:fix"]
  command = "cargo"
  args    = ["clippy", "--fix", "--allow-dirty"]

[tasks.format]
  command = "cargo"
  args    = ["fmt"]

[tasks.clean]
  command = "cargo"
  args    = ["clean"]

[tasks.verify]
  dependencies = ["format", "lint", "clean", "test", "bench", "run"]

[tasks.run]
  command = "cargo"
  args    = ["run", "--release"]

[tasks.bench]
  command = "cargo"
  args    = ["bench"]
